# Generated by Django 6.0.1 on 2026-02-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField()),
                ('addres', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('hobbies', models.CharField(choices=[('playing', 'playing'), ('study', 'study'), ('working', 'working')], max_length=30)),
            ],
            options={
                'db_table': 'studentprofile1',
            },
        ),
    ]
