# Generated by Django 6.0.1 on 2026-02-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_studentprofile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('eating', models.CharField(max_length=20)),
                ('flying', models.CharField(choices=[('yes', 'yes'), ('No', 'No')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='studentprofile1',
            name='addres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile1',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile1',
            name='hobbies',
            field=models.CharField(choices=[('playing', 'playing'), ('study', 'study'), ('working', 'working')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile1',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
