# Generated by Django 6.0.1 on 2026-02-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_animal_alter_studentprofile1_addres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Name',
            new_name='name',
        ),
    ]
