# Generated by Django 6.0.1 on 2026-02-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_name_animal_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
    ]
