# Generated by Django 6.0.1 on 2026-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
