# Generated by Django 6.0.1 on 2026-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_product_produtstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricMachineName', models.CharField(max_length=5)),
                ('electricMachinePrice', models.IntegerField()),
                ('electricMachineStock', models.PositiveBigIntegerField()),
                ('electricMachineWarranty', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'electronicMachine',
            },
        ),
    ]
