# Generated by Django 6.0.1 on 2026-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_electronics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='electricMachineName',
            field=models.CharField(max_length=20),
        ),
    ]
