# Generated by Django 6.0.1 on 2026-02-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='StudentProfile',
        ),
    ]
