# Generated by Django 6.0.1 on 2026-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='electricMachineStock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='electricMachineWarranty',
            field=models.PositiveIntegerField(),
        ),
    ]
