# Generated by Django 6.0.1 on 2026-02-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_electronics_electricmachinestock_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='studentprofile',
        ),
    ]
