# Generated by Django 6.0.1 on 2026-02-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descount',
            field=models.IntegerField(null=True),
        ),
    ]
